### ISSUE TITLE
Snackbar does not default to .SIMPLE when the actionText is null

### ISSUE THREAD

**Issue by Daxito** [bradmartin/nativescript-snackbar#7]
I am using {N} 1.6.1, and even if I set the action text to null I can still see "Close", I am not setting "Close" anywhere BTW.

**Comment by bradmartin** [comment]
Hi @Daxito - I believe the cocoapod for the iOS version defaults to that. @sitefinitysteve and myself discussed this months ago and he integrated the pod.

In the README there is a note:
**Note: To change the "Close" text on iOS edit the info.pList**  which you could try using a empty space there and see if that works. I can't recall if @sitefinitysteve tried that and it crashed. Since there's not a native 'snackbar' component for iOS the cocoapod we chose to use was the best available at the time.  Hope that helps some.

**Comment by Daxito** [comment]
I just checked and it is ok in iOS, but the issue is with Android only.

**Comment by bradmartin** [comment]
So on Android, you see "Close" in the action text when calling the _action_ and _simple_ snackbar?

**Comment by Daxito** [comment]
Yes, I set the text to Null and still see "Close", the same code I use for iOS and see nothing.

**Comment by bradmartin** [comment]
Please share your .JS code so I can test it out. Thanks.

**Comment by Daxito** [comment]
Will do ASAP.

**Comment by Daxito** [comment]
I think the problem is right here in your code:

  // Make sure user sent actionText and actionClickFunction
            // if undefined then we will call .simple using the snackText
            if (!options.actionText) {
                options.actionText = "Close"; //Default value, no need to fallback with promises
            }
